name: CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'src\*'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src\*'

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml
