# Builds a final release version and pushes to nuget.org 
# whenever a release is published.
# Requires: secrets.NUGET_API_KEY

name: Release

on:
  release:
    types: [released]

env:
  DOTNET_NOLOGO: true
  Configuration: Release

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: 🙏 build
        run: dotnet build -p:version=${GITHUB_REF#refs/*/v}

      - name: 🧪 test
        run: dotnet test --no-build --verbosity normal

      - name: 📦 pack
        run: dotnet pack -p:version=${GITHUB_REF#refs/*/v}

      - name: 🚀 nuget
        run: dotnet nuget push "*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
